"""
Django settings for azapp project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z5+f78l*pe^%tb!+e-62#h=wjc0n#f1h#s4!4y%smua2pz!zxx'



# Application definition



ALLOWED_HOSTS = ['*']


BRAND_NAME = 'Switch2VOIP'
CURRENCY = '$'

SETTINGS_EXPORT = [
    'BRAND_NAME',

    'CURRENCY',
]




DJANGO_APPS = [
    'switch2voip.apps.Switch2VoipConfig',
    'carts.apps.CartsConfig',
    'checkout.apps.CheckoutConfig',
    # 'users.apps.UsersConfig',
    'users.apps.UsersConfig',



    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',


    'allauth',
    'allauth.account',





    'paypal.standard.ipn',


]

THIRD_PARTY_APPS = [
    'rest_framework',
    'polymorphic',
    #'django_extensions',
    'apps.cabinet_extension.apps.CabinetConfig',
    #'cabinet',
    'imagefield',
    'easy_thumbnails',
    'ckeditor',
    'ckeditor_uploader',
    'nested_inline',
    # 'stripe',



]

PROJECT_APPS = [
    'apps.core',
    'apps.blog',
    'apps.faq',
    'apps.carty',
    'apps.cart',
    'apps.accounts.apps.UserConfig',
    'payment'
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
]

ROOT_URLCONF = 'azapp.urls'

# AUTH_USER_MODEL = 'users.CustomUser'
#
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


AUTH_USER_MODEL = 'users.CustomUser'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
)
SITE_ID = 2

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"
# ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGOUT_ON_GET = True
LOGIN_REDIRECT_URL = 'users:user_profile'
ACCOUNT_LOGOUT_REDIRECT_URL = 'users:login_signup'
FORCE_SESSION_TO_ONE = False
FORCE_INACTIVE_USER_ENDSESSION = False








TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_settings_export.settings_export',
                'switch2voip.context_processors.categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'azapp.wsgi.application'





DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# CKEDITOR
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default':{
        'toolbar': 'full',
        'height': 768,
        'width': 1024,
        'filebrowserBrowseUrl':'/admin/cabinet/file/?_popup=1',
        'filebrowserImageUrl':'/admin/cabinet/file/?_popup=1&file_type=image_file',
        'filebrowserUploadUrl':'',

    }
}

#easy_thumbnails
THUMBNAIL_ALIASES = {
    '': {
        'avatar': {'size': (50, 50), 'crop': True},
        'size_750x300': {'size': (750, 300), 'crop': True},
    },
}


#cart settings
CART_SESSION_ID = 'cart'


# django-paypal settings

PAYPAL_RECEIVER_EMAIL = 'shaibimaibi501@gmail.com'
PAYPAL_TEST = True

STRIPE_PUBLIC_KEY = 'pk_test_Ug99k9cewdSmXnqJnRKWAbDf00JxqPDq5P'
STRIPE_PRIVATE_KEY = 'sk_test_rr3wMBxFaD0eJCtWvg9xQiow00mNqdldtL'
